import type { StockInfo } from '../types/market.types';

export const STOCKS: StockInfo[] = [
  // Technology (20)
  { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Technology', initialPrice: 175.50 },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', sector: 'Technology', initialPrice: 142.30 },
  { symbol: 'MSFT', name: 'Microsoft Corporation', sector: 'Technology', initialPrice: 380.90 },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', sector: 'Technology', initialPrice: 155.20 },
  { symbol: 'META', name: 'Meta Platforms Inc.', sector: 'Technology', initialPrice: 485.50 },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', sector: 'Technology', initialPrice: 495.20 },
  { symbol: 'TSLA', name: 'Tesla Inc.', sector: 'Technology', initialPrice: 242.80 },
  { symbol: 'NFLX', name: 'Netflix Inc.', sector: 'Technology', initialPrice: 485.30 },
  { symbol: 'ADBE', name: 'Adobe Inc.', sector: 'Technology', initialPrice: 582.40 },
  { symbol: 'CRM', name: 'Salesforce Inc.', sector: 'Technology', initialPrice: 285.60 },
  { symbol: 'ORCL', name: 'Oracle Corporation', sector: 'Technology', initialPrice: 118.30 },
  { symbol: 'INTC', name: 'Intel Corporation', sector: 'Technology', initialPrice: 43.20 },
  { symbol: 'AMD', name: 'Advanced Micro Devices', sector: 'Technology', initialPrice: 165.80 },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.', sector: 'Technology', initialPrice: 51.40 },
  { symbol: 'IBM', name: 'IBM Corporation', sector: 'Technology', initialPrice: 185.70 },
  { symbol: 'QCOM', name: 'Qualcomm Inc.', sector: 'Technology', initialPrice: 142.90 },
  { symbol: 'AVGO', name: 'Broadcom Inc.', sector: 'Technology', initialPrice: 1142.30 },
  { symbol: 'TXN', name: 'Texas Instruments', sector: 'Technology', initialPrice: 172.50 },
  { symbol: 'PYPL', name: 'PayPal Holdings', sector: 'Technology', initialPrice: 62.80 },
  { symbol: 'SQ', name: 'Block Inc.', sector: 'Technology', initialPrice: 78.30 },

  // Finance (15)
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', sector: 'Finance', initialPrice: 185.40 },
  { symbol: 'BAC', name: 'Bank of America', sector: 'Finance', initialPrice: 35.60 },
  { symbol: 'WFC', name: 'Wells Fargo', sector: 'Finance', initialPrice: 52.30 },
  { symbol: 'GS', name: 'Goldman Sachs', sector: 'Finance', initialPrice: 425.80 },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Finance', initialPrice: 95.20 },
  { symbol: 'C', name: 'Citigroup Inc.', sector: 'Finance', initialPrice: 58.70 },
  { symbol: 'V', name: 'Visa Inc.', sector: 'Finance', initialPrice: 267.30 },
  { symbol: 'MA', name: 'Mastercard Inc.', sector: 'Finance', initialPrice: 428.50 },
  { symbol: 'AXP', name: 'American Express', sector: 'Finance', initialPrice: 195.40 },
  { symbol: 'BLK', name: 'BlackRock Inc.', sector: 'Finance', initialPrice: 825.60 },
  { symbol: 'SCHW', name: 'Charles Schwab', sector: 'Finance', initialPrice: 72.40 },
  { symbol: 'USB', name: 'U.S. Bancorp', sector: 'Finance', initialPrice: 46.80 },
  { symbol: 'PNC', name: 'PNC Financial', sector: 'Finance', initialPrice: 165.30 },
  { symbol: 'TFC', name: 'Truist Financial', sector: 'Finance', initialPrice: 42.50 },
  { symbol: 'BK', name: 'Bank of New York Mellon', sector: 'Finance', initialPrice: 58.90 },

  // Healthcare (15)
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Healthcare', initialPrice: 158.30 },
  { symbol: 'UNH', name: 'UnitedHealth Group', sector: 'Healthcare', initialPrice: 528.40 },
  { symbol: 'PFE', name: 'Pfizer Inc.', sector: 'Healthcare', initialPrice: 28.90 },
  { symbol: 'ABBV', name: 'AbbVie Inc.', sector: 'Healthcare', initialPrice: 165.70 },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific', sector: 'Healthcare', initialPrice: 542.30 },
  { symbol: 'ABT', name: 'Abbott Laboratories', sector: 'Healthcare', initialPrice: 112.60 },
  { symbol: 'DHR', name: 'Danaher Corporation', sector: 'Healthcare', initialPrice: 245.80 },
  { symbol: 'BMY', name: 'Bristol Myers Squibb', sector: 'Healthcare', initialPrice: 52.30 },
  { symbol: 'LLY', name: 'Eli Lilly and Company', sector: 'Healthcare', initialPrice: 625.40 },
  { symbol: 'AMGN', name: 'Amgen Inc.', sector: 'Healthcare', initialPrice: 285.60 },
  { symbol: 'GILD', name: 'Gilead Sciences', sector: 'Healthcare', initialPrice: 78.20 },
  { symbol: 'CVS', name: 'CVS Health Corporation', sector: 'Healthcare', initialPrice: 73.50 },
  { symbol: 'CI', name: 'Cigna Group', sector: 'Healthcare', initialPrice: 325.80 },
  { symbol: 'ISRG', name: 'Intuitive Surgical', sector: 'Healthcare', initialPrice: 385.70 },
  { symbol: 'MDT', name: 'Medtronic plc', sector: 'Healthcare', initialPrice: 82.40 },

  // Consumer (15)
  { symbol: 'WMT', name: 'Walmart Inc.', sector: 'Consumer', initialPrice: 165.80 },
  { symbol: 'HD', name: 'Home Depot', sector: 'Consumer', initialPrice: 382.50 },
  { symbol: 'MCD', name: "McDonald's Corporation", sector: 'Consumer', initialPrice: 295.40 },
  { symbol: 'NKE', name: 'NIKE Inc.', sector: 'Consumer', initialPrice: 108.20 },
  { symbol: 'SBUX', name: 'Starbucks Corporation', sector: 'Consumer', initialPrice: 98.60 },
  { symbol: 'TGT', name: 'Target Corporation', sector: 'Consumer', initialPrice: 142.30 },
  { symbol: 'LOW', name: "Lowe's Companies", sector: 'Consumer', initialPrice: 238.70 },
  { symbol: 'TJX', name: 'TJX Companies', sector: 'Consumer', initialPrice: 98.50 },
  { symbol: 'COST', name: 'Costco Wholesale', sector: 'Consumer', initialPrice: 685.30 },
  { symbol: 'KO', name: 'The Coca-Cola Company', sector: 'Consumer', initialPrice: 62.50 },
  { symbol: 'PEP', name: 'PepsiCo Inc.', sector: 'Consumer', initialPrice: 175.40 },
  { symbol: 'PM', name: 'Philip Morris', sector: 'Consumer', initialPrice: 98.70 },
  { symbol: 'MO', name: 'Altria Group', sector: 'Consumer', initialPrice: 48.30 },
  { symbol: 'PG', name: 'Procter & Gamble', sector: 'Consumer', initialPrice: 165.20 },
  { symbol: 'CL', name: 'Colgate-Palmolive', sector: 'Consumer', initialPrice: 88.40 },

  // Energy (10)
  { symbol: 'XOM', name: 'Exxon Mobil Corporation', sector: 'Energy', initialPrice: 112.30 },
  { symbol: 'CVX', name: 'Chevron Corporation', sector: 'Energy', initialPrice: 158.70 },
  { symbol: 'COP', name: 'ConocoPhillips', sector: 'Energy', initialPrice: 118.40 },
  { symbol: 'SLB', name: 'Schlumberger Limited', sector: 'Energy', initialPrice: 52.80 },
  { symbol: 'EOG', name: 'EOG Resources', sector: 'Energy', initialPrice: 128.50 },
  { symbol: 'MPC', name: 'Marathon Petroleum', sector: 'Energy', initialPrice: 165.30 },
  { symbol: 'PSX', name: 'Phillips 66', sector: 'Energy', initialPrice: 142.60 },
  { symbol: 'VLO', name: 'Valero Energy', sector: 'Energy', initialPrice: 145.80 },
  { symbol: 'OXY', name: 'Occidental Petroleum', sector: 'Energy', initialPrice: 58.30 },
  { symbol: 'HAL', name: 'Halliburton Company', sector: 'Energy', initialPrice: 35.70 },

  // Industrials (10)
  { symbol: 'BA', name: 'The Boeing Company', sector: 'Industrials', initialPrice: 185.70 },
  { symbol: 'CAT', name: 'Caterpillar Inc.', sector: 'Industrials', initialPrice: 325.40 },
  { symbol: 'GE', name: 'General Electric Company', sector: 'Industrials', initialPrice: 125.80 },
  { symbol: 'HON', name: 'Honeywell International', sector: 'Industrials', initialPrice: 205.30 },
  { symbol: 'UPS', name: 'United Parcel Service', sector: 'Industrials', initialPrice: 158.60 },
  { symbol: 'LMT', name: 'Lockheed Martin', sector: 'Industrials', initialPrice: 485.20 },
  { symbol: 'RTX', name: 'RTX Corporation', sector: 'Industrials', initialPrice: 98.40 },
  { symbol: 'DE', name: 'Deere & Company', sector: 'Industrials', initialPrice: 425.70 },
  { symbol: 'MMM', name: '3M Company', sector: 'Industrials', initialPrice: 102.30 },
  { symbol: 'FDX', name: 'FedEx Corporation', sector: 'Industrials', initialPrice: 265.80 },

  // Communication (10)
  { symbol: 'DIS', name: 'The Walt Disney Company', sector: 'Communication', initialPrice: 95.60 },
  { symbol: 'CMCSA', name: 'Comcast Corporation', sector: 'Communication', initialPrice: 42.80 },
  { symbol: 'T', name: 'AT&T Inc.', sector: 'Communication', initialPrice: 18.50 },
  { symbol: 'VZ', name: 'Verizon Communications', sector: 'Communication', initialPrice: 41.30 },
  { symbol: 'TMUS', name: 'T-Mobile US', sector: 'Communication', initialPrice: 165.40 },
  { symbol: 'CHTR', name: 'Charter Communications', sector: 'Communication', initialPrice: 385.60 },
  { symbol: 'EA', name: 'Electronic Arts', sector: 'Communication', initialPrice: 142.30 },
  { symbol: 'ATVI', name: 'Activision Blizzard', sector: 'Communication', initialPrice: 95.20 },
  { symbol: 'TTWO', name: 'Take-Two Interactive', sector: 'Communication', initialPrice: 158.70 },
  { symbol: 'WBD', name: 'Warner Bros. Discovery', sector: 'Communication', initialPrice: 12.40 },

  // Real Estate (5)
  { symbol: 'AMT', name: 'American Tower', sector: 'Real Estate', initialPrice: 218.50 },
  { symbol: 'PLD', name: 'Prologis Inc.', sector: 'Real Estate', initialPrice: 142.30 },
  { symbol: 'CCI', name: 'Crown Castle', sector: 'Real Estate', initialPrice: 108.60 },
  { symbol: 'EQIX', name: 'Equinix Inc.', sector: 'Real Estate', initialPrice: 825.40 },
  { symbol: 'SPG', name: 'Simon Property Group', sector: 'Real Estate', initialPrice: 145.80 }
];

export const SECTORS = [
  'Technology',
  'Finance',
  'Healthcare',
  'Consumer',
  'Energy',
  'Industrials',
  'Communication',
  'Real Estate'
];
